name: Build

on:
  push: 
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3
    - name: build
      run: cargo test --verbose